CREATE SCHEMA IF NOT EXISTS tests;

CREATE TABLE IF NOT EXISTS tests.products (
    identifier INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(30),
    price INTEGER CHECK (price > 0)
);

CREATE TABLE IF NOT EXISTS tests.users (
    identifier INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login VARCHAR(30) UNIQUE,
    password VARCHAR(30),
    authentication BOOLEAN DEFAULT FALSE NOT NULL
);